# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba401dadfb33fe40bb19fdf07df2523c89f66e95cfbe44e59fd545eae6f3a26d40f1e16fc9d592c3eb8e7c8ea6bd61f3d7c88d7cf61c5a5f2262593bc7b03ff4

test:
  secret_key_base: 019f28d7ec83980e626fad04044738936cf2607c705a0f229cfdd46c436b16dd8bafed3e93e038f08f8a8fe75eb220e50abf6721411abbb5cbe0c1d4216598e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
